use sort

und zwar teste_bubble_sort
    ls ist liste mit 3 4 2 1
    sorted_ls ist bubble_sort ls
    assert (sorted_ls das ist liste mit 1 2 3 4)
    quasi "bubble sort works"

und zwar teste_merge_sort
    ls ist liste mit 3 4 2 1
    sorted_ls ist merge_sort ls
    assert (sorted_ls das ist liste mit 1 2 3 4)
    quasi "merge sort works"

und zwar main action please
    @teste_bubble_sort
    @teste_merge_sort
